### ISSUE TITLE
Inline HTML Tags and background image doesn't work.

### ISSUE THREAD

**Issue by HinnyTsang** [ralexander-phi/marp-to-pages#10]
Does it seem like the html tags and the background images defined in inline css don't work in the gh-page deploy? 

I have deployed the page from the root folder `/`, and the md file is located in `/docs/` folder, while the images are located in the `/img/` folder. I have also tried to deploy the `/docs/` folder, but it still doesn't work. 

I have set the following line for the background images like the following.

```
marp: true
author: 
header: ''
theme: gaia
math: katex
paginate: true
style: |
    :root {
        background-image: url("./img/background.jpg");
        background-size: contain;
        padding: 3rem;
    }
```

Besides, I have used some html tags like `<p>`, `<span>` and `<small>` in the md file, both the tags and the image shows correctly in the vscode editor, but it doesn't work when deploying on the gh-page.

**Comment by ralexander-phi** [comment]
Hi Hinny,

I can help with this.

The background image issue is due to a difference in how GitHub pages and vscode build URLs. Your HTML slides are trying to load https://www.my-universe.hinnytsang.com/presentation-mcf-project/docs/img/background.jpg (notice the extra /docs/) instead of https://www.my-universe.hinnytsang.com/presentation-mcf-project/img/background.jpg

You may be able to use `url("../img/background.jpg")`, although that may break vscode. You could also try `url("https://www.my-universe.hinnytsang.com/presentation-mcf-project/img/background.jpg")`.

The inline HTML is disabled by by default by marp-cli. Theres a security concern if you are processing marp slides you don't trust. You can edit your `.github/workflows/marp-to-pages.html` to add the  `--html` flag.
https://github.com/marp-team/marp-cli#options

Please let me know if those changes work for you.

**Comment by HinnyTsang** [comment]
@ralexander-phi Thanks, both of them work for me, 
I added the `--html` flag in the `.github\workflows\marp-to-pages.yml` file like this 
![image](https://user-images.githubusercontent.com/46905161/175931531-49ba57c9-0ac5-4b6f-afa8-c3d05166fde4.png)

And changed the URL in the CSS using the direct URL.
